#!/usr/bin/env bash
# Witness for hf7y/scheduler#81: retiring the global RUNNER_CRON field
# safely, i.e. without dropping a tick from any account that has not yet
# been converged by `dose <project> --apply`.
#
# THE RISK (found across three 2026-08-20 comments on #81): once RUNNER_CRON
# is removed from schedule/_runner*.conf, bin/sync-crontab.sh's runner-tier
# block used to hard-refuse ("ERROR ... runner tick omitted") whenever
# RUNNER_CRON was empty, REGARDLESS of why it was empty. Because the managed
# block is always rebuilt from scratch (everything between MARK_BEGIN/
# MARK_END is discarded and replaced by ACCT_LINES), "omitted" meant
# DELETED for any account whose RUNNER line still lived inside that managed
# block -- i.e. every account that had never run `dose <project> --apply`
# even once. Verifying which of the five live accounts had already been
# dose-converged turned out to be blocked from this account (no read access
# to another account's crontab or run.log, no ssh to mandark) -- see #81's
# 2026-08-20T10:45/13:24/16:06 comments. That made "just delete the field"
# unsafe to do blind.
#
# THE FIX doesn't need that cross-account read at all: when RUNNER_CRON is
# absent but RUNNER_JOB/RUNNER_CMD are still set, sync-crontab.sh now reads
# ITS OWN account's current crontab, and if a RUNNER line already sits
# inside the old managed block (tagged "# scheduler:<job>:RUNNER (...)"),
# carries that exact line forward into the new managed block unchanged
# instead of dropping it. An account already dose-converged has its RUNNER
# line OUTSIDE the managed block already (see
# sync-crontab-runner-tag-collision-witness.sh) and is untouched either way.
#
# What must hold:
#   1. RUNNER_CRON absent, an old RUNNER line for this job already sits
#      inside the managed block -> carried forward verbatim, no ERROR.
#   2. RUNNER_CRON absent, no old RUNNER line anywhere -> a note, not an
#      ERROR, and nothing crashes.
#   3. RUNNER_CRON absent from the SHARED conf but a genuine host opt-out
#      (RUNNER_CRON="" written in the host conf while the shared conf still
#      set a value) still behaves as an explicit opt-out, unaffected by the
#      new carry-forward branch.
#
# Runs the REAL script against a throwaway fixture repo, preview-only:
# --apply is never passed, so nothing is ever written to a real crontab.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SYNC="$ROOT/bin/sync-crontab.sh"
[ -f "$SYNC" ] || { echo "script under test not found: $SYNC"; exit 1; }

TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
source "$(dirname "${BASH_SOURCE[0]}")/lib/witness-common.sh"

REPO="$TMP/repo"
mkdir -p "$REPO/bin" "$REPO/lib" "$REPO/schedule" "$REPO/wrappers"
cp -r "$ROOT/bin/." "$REPO/bin/"
cp -r "$ROOT/lib/." "$REPO/lib/"

printf '#!/bin/sh\n' > "$REPO/wrappers/w-runner.sh"; chmod +x "$REPO/wrappers/w-runner.sh"

# One inert project conf is required -- bin/sync-crontab.sh bails out early
# ("no schedule/*.conf entries yet") before it ever reaches RUNNER emission
# when the glob finds zero non-meta confs. Same fixture shape as
# sync-crontab-runner-tag-collision-witness.sh.
: > "$REPO/schedule/_paced.conf"
printf '#!/bin/sh\n' > "$REPO/wrappers/w-inert.sh"; chmod +x "$REPO/wrappers/w-inert.sh"
cat > "$REPO/schedule/w-inert.conf" <<EOF
PROJECT="w-inert"
SWEEP_JOB_NAME=""; SWEEP_SCRIPT=""; SWEEP_CRON=""
BATCH_JOB_NAME=""; BATCH_SCRIPT=""; BATCH_CRON=""
EOF

# Hermetic sudo -- same stub as the sister witness (scheduler#94).
STUBBIN="$TMP/stubbin"; mkdir -p "$STUBBIN"
cat > "$STUBBIN/sudo" <<'STUB'
#!/bin/sh
while [ $# -gt 0 ]; do
  case "$1" in
    -n) shift ;;
    -u) shift; shift ;;
    --) shift; break ;;
    -*) shift ;;
    *) break ;;
  esac
done
exec "$@"
STUB
chmod +x "$STUBBIN/sudo"

# Hermetic crontab -- same stub as the sister witness, preview-only.
CURRENT_CRONTAB_FILE="$STUBBIN/current-crontab.txt"
cat > "$STUBBIN/crontab" <<STUB
#!/bin/sh
if [ "\$1" = "-l" ]; then
  cat "$CURRENT_CRONTAB_FILE"
  exit 0
fi
echo "crontab stub: refusing non -l invocation (args: \$*) -- this witness is preview-only" >&2
exit 9
STUB
chmod +x "$STUBBIN/crontab"
crontab_stub() { printf '%s\n' "$1" > "$CURRENT_CRONTAB_FILE"; }

run_sync() { ( cd "$REPO" && PATH="$STUBBIN:$PATH" "$REPO/bin/sync-crontab.sh" 2>&1 ); }

BEGIN_MARK="# >>> scheduler-managed (generated by bin/sync-crontab.sh -- edit schedule/*.conf instead, then re-run) >>>"
END_MARK="# <<< scheduler-managed <<<"

echo "== RUNNER_CRON retired, an old managed-block RUNNER line already exists"
cat > "$REPO/schedule/_runner.conf" <<EOF
RUNNER_JOB="fixture-paced-runner"
RUNNER_CMD="$REPO/wrappers/w-runner.sh"
RUNNER_ENV="PACED_MAX_PER_TICK=1"
PACED_SUPPRESS_BATCH=1
EOF
OLD_RUNNER_LINE="21 */2 * * * PACED_MAX_PER_TICK=1 $REPO/wrappers/w-runner.sh # scheduler:fixture-paced-runner:RUNNER (usage-paced dispatch)"
crontab_stub "$(printf '%s\n%s\n%s\n' "$BEGIN_MARK" "$OLD_RUNNER_LINE" "$END_MARK")"
OUT="$(run_sync)"
if printf '%s\n' "$OUT" | grep -q "ERROR \[runner\]"; then
  bad "RUNNER_CRON retired but an already-installed tick exists -- got an ERROR instead of carrying it forward"
  echo "$OUT"
elif printf '%s\n' "$OUT" | grep -qF -- "$OLD_RUNNER_LINE"; then
  ok "the previously-installed RUNNER line is carried forward unchanged"
else
  bad "the previously-installed RUNNER line was dropped -- this is the exact tick-loss #81 flagged"
  echo "$OUT"
fi

echo "== RUNNER_CRON retired, no old RUNNER line anywhere (fresh account)"
crontab_stub "0 0 * * * /some/unrelated/cron/job"
OUT="$(run_sync)"
if printf '%s\n' "$OUT" | grep -q "ERROR \[runner\]"; then
  bad "no old tick to carry forward should be a note, not an ERROR"
  echo "$OUT"
else
  ok "nothing to carry forward -- noted, not an error"
fi

echo "== genuine host opt-out (shared conf sets RUNNER_CRON, host conf blanks it) still opts out"
cat > "$REPO/schedule/_runner.conf" <<EOF
RUNNER_JOB="fixture-paced-runner"
RUNNER_CMD="$REPO/wrappers/w-runner.sh"
RUNNER_CRON="0 */6 * * *"
RUNNER_ENV="PACED_MAX_PER_TICK=1"
PACED_SUPPRESS_BATCH=1
EOF
HOST="$(hostname -s 2>/dev/null || hostname 2>/dev/null || echo unknown)"
cat > "$REPO/schedule/_runner.$HOST.conf" <<EOF
RUNNER_CRON=""
EOF
crontab_stub "$(printf '%s\n%s\n%s\n' "$BEGIN_MARK" "$OLD_RUNNER_LINE" "$END_MARK")"
OUT="$(run_sync)"
rm -f "$REPO/schedule/_runner.$HOST.conf"
if printf '%s\n' "$OUT" | grep -q "opts OUT of the runner tick"; then
  ok "an explicit host opt-out still reads as an opt-out, not the retired-field carry-forward path"
else
  bad "explicit host opt-out no longer recognized -- the new carry-forward branch is shadowing it"
  echo "$OUT"
fi

echo
echo "sync-crontab-runner-cron-retired-witness: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ]
